### ISSUE TITLE
Refactor unpacker

### ISSUE THREAD

**Issue by hqucms** [CMS-HGCAL/cmssw#95]
Todos:

- [x] update unpacker and test units
- [ ] factorize the DAQ emulation code 
    -  move from EventFilter to SimCalorimetry/HGCalSimAlgos
- [x] update SlinkFromRaw producer:
    - keep SlinkFromRaw and roc2root in a separate repo: https://gitlab.cern.ch/hgcal-dpg/hgcal-comm
    - [x] `SlinkFromRaw` -> `HGCalSlinkFromRawSource`: [implementation](https://gitlab.cern.ch/hgcal-dpg/hgcal-comm/-/blob/master/SystemTestEventFilters/plugins/HGCalSlinkFromRawSource.cc?ref_type=heads), [example](https://gitlab.cern.ch/hgcal-dpg/hgcal-comm/-/blob/master/SystemTestEventFilters/test/test_slink_source.py?ref_type=heads#L40-48)
    - [ ] `roc2reco`: TODO

**Comment by yulunmiao** [comment]
Here are more detailed todos in "update unpacker and test units"
- [x] Delete code for Capture Block and ECON-D unpacking
- [x] Add code and test the proposal where we book SOA with denseIdx first and fill it
- [x] Add/modify classes to include S-Link header, trailer info, Capture Block header info, and ECON-D trailer info and modify code for "header-only" unpacking
- [x] Modify code to do "header-only", "digis-only", and inclusive unpacking
- [x] test with comparison to test beam re-reco

**Comment by yulunmiao** [comment]
@pfs @hqucms I checked the code and find that the subpackage EventFilter/HGCalRawToDigi in the dev branch is out of date, the most up-to-date version is in branch https://github.com/CMS-HGCAL/cmssw/tree/hgcal-condformat-HGCalNANO-13_2_0_pre3. Huiling suggested to copy by hand. Should I proceed with this and push to this branch so we have the correct starting point?

**Comment by pfs** [comment]
Hi @yulunmiao indeed we need to copy by hand just the bare files which we want to make part of the new pull request. 
We have to coordinate among us all for the following:
- SlinkFromRaw producer : move to hgcal-comm: @hqucms 
- Emulators : move to SimCalorimetry/HGCalSimAlgos : @pfs 
- Unpacker stuff: develop under EventFilter where it is: @yulunmiao 
anything else?

**Comment by yulunmiao** [comment]
@pfs Judged by checking the header files used in [HGCalRawToDigi.cc](https://github.com/CMS-HGCAL/cmssw/blob/hgcal-condformat-HGCalNANO-13_2_0_pre3/EventFilter/HGCalRawToDigi/plugins/HGCalRawToDigi.cc) We should also include things in DataFormats(mostly SOA related stuff) and CondFormats(module information).

**Comment by pfs** [comment]
ah right so we need the SoA for the digis but nothing in condformats, that we'll use what's in https://github.com/cms-sw/cmssw/pull/43751

**Comment by yulunmiao** [comment]
Great, do we also want to keep the digi to reco step, so we can do the comparison to the beam re-reco. In this case, we might also need to add Yuwei or Jeremi here to move the necessary subpackages to this branch. Otherwise, the only thing we can compare is the digis unpacked by the unpacker.

**Comment by pfs** [comment]
I think we can close this one: after all the new version was extensively used and debugged in the testbeams :)
There is a remaining item that is to revive the realistic DIGIs emulation but it should be taken on a different issue.
